title: 'Navigation Settings'
data:
  links_direction: right
  sticky: true
  shrinkable: false
  nav_controlled_header: true
  navigation_hero:
    -
      image:
        - p1100706-2.jpg
      type: navigation_hero_image
      enabled: true
    -
      image:
        - ayadi-ghaith-dbxdqkfspni-unsplash.jpg
      type: navigation_hero_image
      enabled: true
    -
      image:
        - lucia-garo-suxtl0pzwwm-unsplash.jpg
      type: navigation_hero_image
      enabled: true
    -
      image:
        - mario-esposito-8pympjx4288-unsplash.jpg
      type: navigation_hero_image
      enabled: true
  footer_sticky: false
