sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: price
        field:
          display: price
          type: integer
          icon: integer
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
      -
        handle: image
        field:
          mode: list
          container: images
          restrict: false
          allow_uploads: true
          show_filename: true
          display: image
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          localizable: true
title: product
